/*
  GlobalLeaderboardPage.jsx

  The global leaderboard answers:

    "Across all tags, which commander-tag combinations are most unusual?"

  For the first Chat 10 version, this page loads global_leaderboard.json.
  That file is already default-filtered by the Python analysis pipeline.
  The frontend then adds user-controlled filters and sorting.
*/

import { useEffect, useMemo, useState } from "react";

import DataTable from "../components/DataTable";
import SmallBarChart from "../components/SmallBarChart";
import TableFilters from "../components/TableFilters";

import { createLeaderboardColumns } from "../lib/tableColumns";

import {
  buildTagOptionsFromRows,
  formatNumber,
  makeTopZChartData,
  rowMatchesLeaderboardFilters,
} from "../lib/filterUtils";

const GLOBAL_LEADERBOARD_PATH = "/data/latest/global_leaderboard.json";

async function loadJson(path) {
  const response = await fetch(path);

  if (!response.ok) {
    throw new Error(`Could not load ${path}. HTTP status: ${response.status}`);
  }

  return response.json();
}

export default function GlobalLeaderboardPage() {
  const [rows, setRows] = useState([]);
  const [loadState, setLoadState] = useState({
    loading: true,
    error: "",
  });

  const [filters, setFilters] = useState({
    commanderText: "",
    tagText: "",
    colorIdentity: "",
    minTotalDecks: "200",
    minTagDecks: "5",
    minZ: "",
    minAffinityPct: "",
    trendStatus: "",
  });

  useEffect(() => {
    let isMounted = true;

    async function loadLeaderboard() {
      try {
        const loadedRows = await loadJson(GLOBAL_LEADERBOARD_PATH);

        if (!Array.isArray(loadedRows)) {
          throw new Error("global_leaderboard.json did not contain an array.");
        }

        if (isMounted) {
          setRows(loadedRows);
          setLoadState({
            loading: false,
            error: "",
          });
        }
      } catch (error) {
        if (isMounted) {
          setLoadState({
            loading: false,
            error: error.message,
          });
        }
      }
    }

    loadLeaderboard();

    return () => {
      isMounted = false;
    };
  }, []);

  const columns = useMemo(() => createLeaderboardColumns(), []);

  const tagOptions = useMemo(() => buildTagOptionsFromRows(rows), [rows]);

  const filteredRows = useMemo(() => {
    return rows.filter((row) => rowMatchesLeaderboardFilters(row, filters));
  }, [rows, filters]);

  const chartData = useMemo(() => {
    return makeTopZChartData(filteredRows, 10);
  }, [filteredRows]);

  if (loadState.loading) {
    return (
      <main className="page">
        <p>Loading global leaderboard...</p>
      </main>
    );
  }

  if (loadState.error) {
    return (
      <main className="page">
        <h1>Global Leaderboard</h1>
        <p className="error-message">{loadState.error}</p>
        <p>
          Check that <code>{GLOBAL_LEADERBOARD_PATH}</code> exists inside{" "}
          <code>frontend/public/data/latest/</code>.
        </p>
      </main>
    );
  }

  return (
    <main className="page">
      <section className="page-header">
        <p className="eyebrow">Chat 10</p>
        <h1>Global Leaderboard</h1>
        <p>
          Browse commander-tag pairs across all tags, sorted and filtered by
          statistical affinity. This page starts from the default-filtered
          leaderboard generated by the Python analysis pipeline.
        </p>
      </section>

      <section className="stat-row">
        <article className="stat-card">
          <span>Loaded rows</span>
          <strong>{formatNumber(rows.length)}</strong>
        </article>

        <article className="stat-card">
          <span>Rows after filters</span>
          <strong>{formatNumber(filteredRows.length)}</strong>
        </article>

        <article className="stat-card">
          <span>Available tags</span>
          <strong>{formatNumber(tagOptions.length)}</strong>
        </article>
      </section>

      <TableFilters
        mode="leaderboard"
        filters={filters}
        setFilters={setFilters}
        tagOptions={tagOptions}
      />

      <SmallBarChart
        title="Top z-scores in current filters"
        description="This chart summarizes the strongest visible commander-tag affinities after your current filters."
        data={chartData}
        xKey="name"
        yKey="value"
      />

      <DataTable
        data={filteredRows}
        columns={columns}
        tableLabel="Global commander-tag leaderboard"
        initialSorting={[{ id: "z", desc: true }]}
        pageSize={25}
      />
    </main>
  );
}