import { useEffect, useState } from "react";
import {
  loadAnalysisSummary,
  loadGlobalLeaderboard,
  loadTagSummary,
  loadTrendSummary,
} from "../lib/api.js";
import { formatNumber } from "../lib/formatters.js";
import StatCard from "../components/StatCard.jsx";
import LoadingState from "../components/LoadingState.jsx";
import ErrorState from "../components/ErrorState.jsx";

/*
  HomePage proves that the React app can load the processed JSON files.

  It does not load the giant affinity_rows_with_trends.json file.
  That file is only loaded on the Commander Search page.
*/

export default function HomePage() {
  const [data, setData] = useState({
    analysisSummary: null,
    trendSummary: null,
    tagSummary: null,
    leaderboard: null,
  });

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadHomeData() {
      try {
        const [
          analysisSummary,
          trendSummary,
          tagSummary,
          leaderboard,
        ] = await Promise.all([
          loadAnalysisSummary(),
          loadTrendSummary(),
          loadTagSummary(),
          loadGlobalLeaderboard(),
        ]);

        setData({
          analysisSummary,
          trendSummary,
          tagSummary,
          leaderboard,
        });
      } catch (caughtError) {
        setError(caughtError);
      } finally {
        setLoading(false);
      }
    }

    loadHomeData();
  }, []);

  if (loading) {
    return <LoadingState message="Loading project summary..." />;
  }

  if (error) {
    return <ErrorState title="Could not load homepage data" error={error} />;
  }

  const { analysisSummary, trendSummary, tagSummary, leaderboard } = data;

  return (
    <div className="page">
      <section className="hero">
        <p className="eyebrow">Chat 9 Website Prototype</p>

        <h1>Commander tag affinity, adjusted by tag context.</h1>

        <p className="hero__text">
          This site analyzes which EDHREC commanders are unusually associated
          with specific deckbuilding tags. Instead of only showing popularity,
          it highlights commander-tag relationships using affinity percentage,
          z-score, rank, percentile, and eventually historical movement.
        </p>
      </section>

      <section className="section">
        <div className="section-heading">
          <h2>Latest processed dataset</h2>
          <p>
            These values are loaded from the static JSON files generated by the
            Python pipeline.
          </p>
        </div>

        <div className="stat-grid">
          <StatCard
            label="Affinity rows"
            value={formatNumber(analysisSummary.affinity_row_count)}
            helper="Full analyzed commander-tag rows."
          />

          <StatCard
            label="Leaderboard rows"
            value={formatNumber(analysisSummary.global_leaderboard_row_count)}
            helper="Rows passing default sample-size filters."
          />

          <StatCard
            label="Commanders"
            value={formatNumber(analysisSummary.unique_commander_count)}
            helper="Commanders with at least one usable tag row."
          />

          <StatCard
            label="Tags"
            value={formatNumber(analysisSummary.unique_tag_count)}
            helper="Normal tags plus cEDH when present."
          />
        </div>
      </section>

      <section className="section two-column">
        <article className="panel">
          <h2>Trend status</h2>

          {trendSummary.previous_snapshot_found ? (
            <p>
              This dataset was compared against{" "}
              <strong>{trendSummary.previous_snapshot}</strong>.
            </p>
          ) : (
            <p>
              No previous processed snapshot exists yet. Trend fields are
              present in the data shape, but real movement begins after the
              second completed scrape-clean-analysis cycle.
            </p>
          )}

          <dl className="summary-list">
            <div>
              <dt>Current snapshot</dt>
              <dd>{trendSummary.current_snapshot || "Unavailable"}</dd>
            </div>

            <div>
              <dt>Trend rows</dt>
              <dd>{formatNumber(trendSummary.trend_row_count)}</dd>
            </div>

            <div>
              <dt>No previous snapshot rows</dt>
              <dd>{formatNumber(trendSummary.no_previous_snapshot_count)}</dd>
            </div>
          </dl>
        </article>

        <article className="panel">
          <h2>Data files loaded</h2>

          <ul className="check-list">
            <li>analysis_summary.json</li>
            <li>trend_summary.json</li>
            <li>tag_summary.json</li>
            <li>global_leaderboard.json</li>
          </ul>

          <p className="muted">
            The larger affinity table is loaded only on the commander search
            page to keep the homepage lighter.
          </p>
        </article>
      </section>

      <section className="section">
        <div className="section-heading">
          <h2>Sample leaderboard rows</h2>
          <p>
            This preview uses the first five rows from global_leaderboard.json.
            Chat 10 will replace this with a proper sortable table.
          </p>
        </div>

        <div className="simple-table-wrap">
          <table className="simple-table">
            <thead>
              <tr>
                <th>Commander</th>
                <th>Tag</th>
                <th>Total decks</th>
                <th>Tag decks</th>
                <th>Z-score</th>
              </tr>
            </thead>

            <tbody>
              {leaderboard.slice(0, 5).map((row) => (
                <tr key={`${row.commander_slug}-${row.tag_slug}`}>
                  <td>{row.commander_name}</td>
                  <td>{row.tag_name}</td>
                  <td>{formatNumber(row.total_decks)}</td>
                  <td>{formatNumber(row.tag_decks)}</td>
                  <td>{row.z == null ? "—" : Number(row.z).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="muted">
          Tag summary rows loaded: {formatNumber(tagSummary.length)}
        </p>
      </section>
    </div>
  );
}